name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        shell: bash
        run: |
          # App név kiolvasása az angular.json-ból
          APP=$(node -e "const a=require('./angular.json'); console.log(Object.keys(a.projects)[0])")
          echo "Detected Angular project: $APP"

          # Build - projekt oldal: /cadentis/
          npx ng build --configuration production \
            --base-href "/cadentis/" \
            --deploy-url "/cadentis/"

          # Kimeneti mappa autodetekció (Angular 17/18: dist/<app>/browser)
          if [ -d "dist/$APP/browser" ]; then
            OUT_DIR="dist/$APP/browser"
          else
            OUT_DIR="dist/$APP"
          fi
          echo "OUT_DIR=$OUT_DIR" >> $GITHUB_ENV
          ls -la "$OUT_DIR"
          test -f "$OUT_DIR/index.html" || (echo "index.html not found in $OUT_DIR" && exit 1)

      - name: Add SPA 404 fallback
        run: cp "$OUT_DIR/index.html" "$OUT_DIR/404.html"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ${{ env.OUT_DIR }}
          force_orphan: true
